version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    environment:
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=80
    volumes:
      - .:/app
    ports:
      - "80:80"
